version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
        # Mount PHP for each domain's public folder:

        # pablo.camara.pt:
      - ./sites/pablo.camara.pt/root/public/:/var/www/pablo.camara.pt/public
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    container_name: pc_mysql
    volumes:
      - ./docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_main_pwd2019
      MYSQL_DATABASE: pablocamara
      MYSQL_USER: pc_main_user2019
      MYSQL_PASSWORD: pc_main_user_pwd2019
    ports:
      - 3306:3306
  nginx:
    build:
      context: ./docker/nginx
    volumes:
        #Nginx Global Configurations
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d

        #Nginx Configurations for you Sites:

        # pablo.camara.pt:
        # - Nginx Server block
      - ./sites/pablo.camara.pt/site.conf:/etc/nginx/sites-available/pablo.camara.pt.conf
        # - Current Cloudflare certificates
      #- ./sites/pablo.camara.pt/certificates/:/etc/nginx/sites/pablo.camara.pt/certificates
        # - Copy Public Folder:
      #- ./sites/pablo.camara.pt/root/public/:/var/www/pablo.camara.pt/public


    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    restart: always
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pc_phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
          - 9999:80
      links:
          - mysql